# Generated by Django 3.0.6 on 2020-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('drsno', models.CharField(max_length=50)),
                ('conno', models.CharField(max_length=15)),
                ('pcs', models.CharField(max_length=10)),
                ('wth', models.CharField(max_length=10)),
                ('boy', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='areaname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='delboys',
            name='boyname',
            field=models.CharField(max_length=40),
        ),
    ]
