# Generated by Django 3.0.6 on 2020-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0002_auto_20200721_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummydrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummydrs', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='drsdata',
            name='conno',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='drsdata',
            name='pcs',
            field=models.IntegerField(),
        ),
    ]
