# Generated by Django 3.0.6 on 2020-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0003_auto_20200723_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drsdata',
            name='drsno',
        ),
        migrations.AlterField(
            model_name='dummydrs',
            name='dummydrs',
            field=models.IntegerField(),
        ),
    ]
